on: [workflow_dispatch] 
 
jobs:
  findsecbugs:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
        
    
    - name: test
      run : |
       
       docker images
       docker pull vishalceg/findsecbugs
       echo  ${{github.workspace}}
       docker run -v ${{github.workspace}}:/workdir/scan vishalceg/findsecbugs 
