on: [workflow_dispatch] 
 
jobs:
  findsecbugs:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: findsecbugs
      run : |
       
       docker images
       docker pull vishalceg/findsecbugs
       echo  ${{github.workspace}}
       docker run -v ${{github.workspace}}:/workdir/scan vishalceg/findsecbugs 
       ls ${{github.workspace}}
       cat ${{github.workspace}}/secbugs-output.xml
    - name: Self dep-scan
      run : |
       
       docker images
       docker pull quay.io/appthreat/dep-scan
       echo  ${{github.workspace}}      
       docker run --rm -v  ${{github.workspace}}:/app appthreat/dep-scan scan --src /app --report_file /app/reports/depscan.json
    - name: ls
      run: |
       ls ${{github.workspace}}/reports
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
       # GITHUB_TOKEN: ${{ secrets.SL_TOKEN }}
      #  SCAN_AUTO_BUILD: true
        SCAN_ANNOTATE_PR: true
      with:
        output: reports
        # Scan auto-detects the languages in your project. To override uncomment the below variable and set the type
        type: depscan
    
      
       
       
