on: [workflow_dispatch] 
 
jobs:
  findsecbugs:
    runs-on: ubuntu-latest
   
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: findsecbugs
      run : |
       
       docker images
       docker pull vishalceg/findsecbugs
       echo  ${{github.workspace}}
       docker run -v ${{github.workspace}}:/workdir/scan vishalceg/findsecbugs 
       ls ${{github.workspace}}
       cat ${{github.workspace}}/secbugs-output.xml
    - uses: sburris/dependency-check-action@master
      with:
        Project-Name: "Ecom-service"
        Report-Format: 'JSON'
        
   # - name: Perform Scan
   #   run : |
   #    docker pull owasp/dependency-check:latest
   #    docker run --rm --volume ${{github.workspace}}:/src --volume ${{github.workspace}}:/usr/share/dependency-check/data --volume ${{github.workspace}}:/report  owasp/dependency-check:latest --scan /src --format "JSON" --project "ecom-service"  --out /report
    
      
       
       
