on: [push,workflow_dispatch] 
 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: bhuvi11/Test_action@v3
      with:
        who-to-greet: 'Testing for bhuvi repository action'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
    - run: echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
      shell: bash
    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt 

    - uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: path/to/artifact/world.txt
    - uses: actions/download-artifact@v2
      with:
       name: my-artifact
       path: path/to/artifact 
  
