on: [push,workflow_dispatch] 
 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: bhuvi11/Test_action@v3
      with:
        who-to-greet: 'Testing for bhuvi repository action'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash
    - uses: actions/download-artifact@v2
    - id: download
      with:
        name: 'my-artifact'
        path: path/to/artifacts
