name: Securin SL Scanning
on: [workflow_dispatch]
jobs:
  job-test:
     runs-on: ubuntu-latest
     steps:
     - run: |
        token=$( curl --request POST 'http://dae90d7ec0a9.ngrok.io/api/get_token' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "userId": "vishal.kumar@cybersecurityworks.com",
                     "password": "Vishal123#"
                }' | jq '.access_token' )
        echo "AUTH_TOKEN=$token" >> "$GITHUB_ENV"

     - run: echo "$AUTH_TOKEN"
     - run: | 
          curl --location --request GET 'http://801f8f58e508.ngrok.io/scaninfo' \
             --header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJNalJscjVlb1VlN3RSTXhSMUVvUW1Cek5rWGRuVnM2NVVXa2ZpQ3F5LXBnIn0.eyJqdGkiOiI5M2YyMTZkNi03YmE0LTRkOTItODNjMy0zZGE4YzFiYTgzNTMiLCJleHAiOjE2Mjg1MjUyNTQsIm5iZiI6MCwiaWF0IjoxNjI4NTIxNjU0LCJpc3MiOiJodHRwczovL2F1dGh0ZXN0LnNlY3VyaW4uaW8vYXV0aC9yZWFsbXMvQ1NXLURldiIsImF1ZCI6WyJlbGFzdGljLWluZ2VzdGlvbi1hcGkiLCJjb250cmFjdC1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiIzMjgyMzY3OC00ODAzLTQ5YmMtOGQ1NC01NzRkMjdkZTUzNTgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyaXNrLXF1b3RpZW50IiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiOWJmNWEyNzQtN2NmMC00ODc0LWFmODQtNDE2OWIzZmEwNTg2IiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19LCJyaXNrLXF1b3RpZW50Ijp7InJvbGVzIjpbImNzdyBzdXBlciBhZG1pbiJdfX0sInNjb3BlIjoic3VwZXJfYWRtaW5fc2NvcGUgaW50ZXJuYWwtdXNlcnMtc2NvcGUgcHJvZmlsZSBlbWFpbCBhZG1pbiIsImFjY291bnRJZCI6IjEyOSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJ1c2VyLWlkIjoiMzI4MjM2NzgtNDgwMy00OWJjLThkNTQtNTc0ZDI3ZGU1MzU4IiwibmFtZSI6IlZpc2hhbCBrdW1hciIsInByZWZlcnJlZF91c2VybmFtZSI6InZpc2hhbC5rdW1hckBjeWJlcnNlY3VyaXR5d29ya3MuY29tIiwiZ2l2ZW5fbmFtZSI6IlZpc2hhbCIsImZhbWlseV9uYW1lIjoia3VtYXIiLCJlbWFpbCI6InZpc2hhbC5rdW1hckBjeWJlcnNlY3VyaXR5d29ya3MuY29tIn0.ENLDjxCkxsbXkozuCzx2tcNprnXHv7SSOeTOWp1BM78IZdCIxHAhJLkE_x6-q3jICjHXPZbh1OLYrKt5ZLi2TymfRWDNMNxzXuNUjH2YJxX6zCQu_rGaVILSyHQCur7WRGK6Njx5UrVbc-xz5PSKdQkk52sMQ5h4Iz5UbudrggUss9PomKR6JNLyizThpcqBvv43uNmfgwFGggRUDKOwcf6Yuu6yeADRA_VEp9stx-Fj_Ltxeq02JP2IrgbJX6az2pqecc6Te0fiiGwOcMH42QWTyWvMxUSJPAkPG-KXJC8xVK19nN11hnqPoowuIsbAjj-_tJCA435v5OMOr2AWbw' \
             --data-raw ''
     
  job-a:
    runs-on: ubuntu-latest
    outputs:
      auth_token: ${{ steps.get-token.outputs.auth_token }}
    steps:
     - id: get-token
       run: |
           token=$( curl --request POST 'http://dae90d7ec0a9.ngrok.io/api/get_token' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "userId": "vishal.kumar@cybersecurityworks.com",
                     "password": "Vishal123#"
                }' | jq '.access_token' )
           echo "::set-output name=auth_token::hello"
          
      
  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
    - name: Logging to Docker
      run: | 
          curl --location --request GET 'http://801f8f58e508.ngrok.io/scaninfo' \
             --header 'Authorization: Bearer ${{needs.job-a.outputs.auth_token}}' \
             --data-raw ''
    - name: Print token
      run: echo ${{ needs.job-a.outputs.auth_token }}
            
                       
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Anchore Engine
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - uses: anchore/scan-action@v2
      id: scan
      with:
        image: "localbuild/testimage:latest"
            
   # - name: grype scan JSON results
  #  run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}      
    - name: Bridgecrew
      uses: bridgecrewio/checkov-action@master
      with:
          directory: ${{github.workspace}}/
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: json # optional: the output format, one of: cli, json, junitxml, github_failed_only
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          log_level: DEBUG # optional: set log level. Default WARNING
    - name: Findsecbugs
      run : |
       
       docker images
       docker pull vishalceg/findsecbugs
       echo  ${{github.workspace}}
       docker run -v ${{github.workspace}}:/workdir/scan vishalceg/findsecbugs 
       cat ${{github.workspace}}/secbugs-output.xml
    - name: OWASP Dependency Checker
      run : |
       
       docker images
       docker pull securetest1/owasp
       echo  ${{github.workspace}}
       docker run -v ${{github.workspace}}:/src  --volume ${{github.workspace}}:/reports  securetest1/owasp --project "ECOM-SERVICE" --disableAssembly --disableNodeJS --disableRetireJS 
       ls ${{github.workspace}}
       cat ${{github.workspace}}/dependency-check-report.json
