---
name: Securin Scan
"on":
- workflow_dispatch
- pull_request
jobs:
  scanning:
    env:
      TRIVY_IMAGE_TAG: 535827507377.dkr.ecr.us-west-2.amazonaws.com/trivy:latest
    steps:
    - name: Retrieve Token
      run: |
        token=$( curl --request POST 'http://f8f3-103-70-41-11.ngrok.io/api/get_token'  --header 'Content-Type: application/json'  --data-raw  '{"userId": "${{ secrets.USER_NAME }}", "password": "${{ secrets.PASSWORD }}" }' | jq -r '.access_token' )
        echo "AUTH_TOKEN=$token" >> $GITHUB_ENV
    - run: |
        respJson=$(curl --location --request GET 'http://07cc-103-70-41-11.ngrok.io/auth-token'  --header 'Authorization: Bearer ${{ env.AUTH_TOKEN }}'  --data-raw ' ' )
        echo "AUTH_USER=$(jq -r '.user' <<< "$respJson")" >> $GITHUB_ENV
        echo "AUTH_PASSWORD=$(jq -r '.password' <<< "$respJson")" >> $GITHUB_ENV
        echo "AUTH_PROXYURL=$(jq -r '.proxyUrl' <<< "$respJson")" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Set up java 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Build Image
      run: docker build -t localbuild/testimage:latest .
    - name: Container Scan
      run: |
        docker login --username  ${{ env.AUTH_USER }} --password ${{ env.AUTH_PASSWORD }} ${{ env.AUTH_PROXYURL }}
        docker pull ${{env.TRIVY_IMAGE_TAG}}
        docker run -v ${{github.workspace}}:/root/ ${{env.TRIVY_IMAGE_TAG}} -f json -o /root/trivy-result.json localbuild/testimage
        echo $(cat ${{github.workspace}}/trivy-result.json) > trivy-report.json
    - uses: actions/upload-artifact@v2
      with:
        name: shiftleft
        path: trivy-report.json
    runs-on: ubuntu-latest
  Analysing-results:
    needs: scanning
    steps:
    - name: Result parsing
      run: |
        token=$( curl --request POST 'http://f8f3-103-70-41-11.ngrok.io/api/get_token'  --header 'Content-Type: application/json'  --data-raw  '{"userId": "${{ secrets.USER_NAME }}", "password": "${{ secrets.PASSWORD }}" }' | jq -r '.access_token' )
        echo "AUTH_TOKEN=$token" >> $GITHUB_ENV
        echo "PULL_ID=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
    - name: Download Scan Result
      uses: actions/download-artifact@v2
      with:
        name: shiftleft
    - run: |
        result=$(curl --location --request POST 'http://07cc-103-70-41-11.ngrok.io/github/notify'  --header 'Authorization: Bearer ${{ env.AUTH_TOKEN }}' --form 'file=@"trivy-report.json"' --form 'repo="${{ github.repository }}"' --form 'event="${{ github.event_name }}"' --form 'pull_id="${{ env.PULL_ID }}"')
        echo $(jq -r '.serifdata' <<< "$result") > result.sarif
        echo $(jq -r '.consoleResult' <<< "$result") > consoleResult.txt
        echo "BUILD_STATUS=$(jq -r '.buildStatus' <<< "$result")" >> $GITHUB_ENV
        echo "SARIF_GEN=$(jq -r '.generateSarif' <<< "$result")" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: shiftleft
        path: result.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: result.sarif
      if: ${{ env.SARIF_GEN == 'true' }}
    - name: Print result on console
      run: |-
        value=`cat consoleResult.txt`
        echo $value
    - name: Fail the build
      run: |-
        echo "Found issues"
        exit 1
      if: ${{ env.BUILD_STATUS == 'false' }}
    runs-on: ubuntu-latest
