---
name: Shiftleft Scan
"on":
- workflow_dispatch
jobs:
  scanning:
    env:
      FINDSECBUG_IMAGE_TAG: 442752979892.dkr.ecr.us-east-2.amazonaws.com/findsecbugs:latest
    steps:
    - name: Retrieve Token
      run: |
        token=$( curl --request POST 'http://111fc94ef71f.ngrok.io/api/get_token'  --header 'Content-Type: application/json'  --data-raw  '{"userId": "${{ secrets.USER_NAME }}", "password": "${{ secrets.PASSWORD }}" }' | jq -r '.access_token' )
        echo "AUTH_TOKEN=$token" >> $GITHUB_ENV
    - run: |
        respJson=$(curl --location --request GET 'http://157fb3e4a848.ngrok.io/auth-token'  --header 'Authorization: Bearer ${{ env.AUTH_TOKEN }}'  --data-raw ' ' )
        echo "AUTH_USER=$(jq -r '.user' <<< "$respJson")" >> $GITHUB_ENV
        echo "AUTH_PASSWORD=$(jq -r '.password' <<< "$respJson")" >> $GITHUB_ENV
        echo "AUTH_PROXYURL=$(jq -r '.proxyUrl' <<< "$respJson")" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Set up java 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Findsecbugs Scan
      run: |
        docker login --username  ${{ env.AUTH_USER }} --password ${{ env.AUTH_PASSWORD }} ${{ env.AUTH_PROXYURL }}
        docker pull ${{env.FINDSECBUG_IMAGE_TAG}}
        echo  ${{github.workspace}}
        docker run -v ${{github.workspace}}:/workdir/scan ${{env.FINDSECBUG_IMAGE_TAG}}
        echo $(cat ${{github.workspace}}/secbugs-output.xml) > secbugs.xml
    - uses: actions/upload-artifact@v2
      with:
        name: shiftleft
        path: secbugs.xml
    runs-on: ubuntu-latest
  result_processing:
    needs: scanning
    steps:
    - name: Result parsing
      run: |
        token=$( curl --request POST 'http://111fc94ef71f.ngrok.io/api/get_token'  --header 'Content-Type: application/json'  --data-raw  '{"userId": "${{ secrets.USER_NAME }}", "password": "${{ secrets.PASSWORD }}" }' | jq -r '.access_token' )
        echo "AUTH_TOKEN=$token" >> $GITHUB_ENV
    - name: Download math result for job 2
      uses: actions/download-artifact@v2
      with:
          name: shiftleft
    - name: Print the final result
      run: |
          value=$(cat secbugs.xml)
          echo "FINDSECBUGRESULT=$value" >> $GITHUB_ENV
          echo The result is $value  
    - run: |      
          respJson=$(curl --location --request POST 'http://157fb3e4a848.ngrok.io/github/notify'  --header 'Authorization: Bearer ${{ env.AUTH_TOKEN }}'  --form 'file=@"secbugs.xml"' --form 'repo="${{ github.repository }}"' )

    runs-on: ubuntu-latest
