---
name: Shiftleft Scan
"on":
- workflow_dispatch
jobs:     
  scanning:
    env:
      FINDSECBUG_IMAGE_TAG: 442752979892.dkr.ecr.us-east-2.amazonaws.com/findsecbugs:latest
      REPO_NAME: vishal-ceg
    steps:
    - name: Retrieve Token
      run: |
        echo ${{env.REPO_NAME}}
        token=$( curl --request POST 'http://1b1a164eaf40.ngrok.io/api/get_token'  --header 'Content-Type: application/json'  --data-raw  '{"userId": "${{ secrets.USER_NAME }}", "password": "${{ secrets.PASSWORD }}" }' | jq -r '.access_token' )
        echo "AUTH_TOKEN=$token" >> $GITHUB_ENV
    - run: |
        respJson=$(curl --location --request GET 'http://5319733bfa40.ngrok.io/auth-token'  --header 'Authorization: Bearer ${{ env.AUTH_TOKEN }}'  --data-raw ' ' )
        echo "AUTH_USER=$(jq -r '.user' <<< "$respJson")" >> $GITHUB_ENV
        echo "AUTH_PASSWORD=$(jq -r '.password' <<< "$respJson")" >> $GITHUB_ENV
        echo "AUTH_PROXYURL=$(jq -r '.proxyUrl' <<< "$respJson")" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Set up java 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Findsecbugs Scan
      run: |
        docker login --username  ${{ env.AUTH_USER }} --password ${{ env.AUTH_PASSWORD }} ${{ env.AUTH_PROXYURL }}
        docker pull ${{env.FINDSECBUG_IMAGE_TAG}}
        echo  ${{github.workspace}}
        docker run -v ${{github.workspace}}:/workdir/scan ${{env.FINDSECBUG_IMAGE_TAG}}
        echo $(cat ${{github.workspace}}/secbugs-output.xml) > secbugs.xml
    - uses: actions/upload-artifact@v2
      with:
        name: shiftleft
        path: secbugs.xml
    runs-on: ubuntu-latest
  result_processing:
    steps:
    - name: Result parsing
      run: echo Result processing completed!
    - run: echo ${{env.GITHUB_RUN_ID}}
    runs-on: ubuntu-latest
