---
name: Shiftleft Scan
"on":
- workflow_dispatch
jobs:
  step1:
    env:
      FINDSECBUG_IMAGE_TAG: 442752979892.dkr.ecr.us-east-2.amazonaws.com/findsecbugs:latest
    steps:
    - name: Retrieve Token
      run: |
        token=$( curl --request POST 'http://localhost:4444/api/get_token'  --header 'Content-Type: application/json'  --data-raw  '{"userId": "vishal.kumar@cybersecurityworks.com", "password": "Vishal123#" }' | jq -r '.access_token' )
        echo "AUTH_TOKEN=$token" >> $GITHUB_ENV
    - run: |
        respJson=$(curl --location --request GET 'http://localhost:4444/auth-token'  --header 'Authorization: Bearer ${{ env.AUTH_TOKEN }}'  --data-raw ' ' )
        echo "AUTH_USER=$(jq -r '.user' <<< "$respJson")" >> $GITHUB_ENV
        echo "AUTH_PASSWORD=$(jq -r '.password' <<< "$respJson")" >> $GITHUB_ENV
        echo "AUTH_PROXYURL=$(jq -r '.proxyUrl' <<< "$respJson")" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Set up java 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Findsecbugs Scan
      run: |
        docker login --username  ${{ env.AUTH_USER }} --password ${{ env.AUTH_PASSWORD }} ${{ env.AUTH_PROXYURL }}
        docker pull ${{env.FINDSECBUG_IMAGE_TAG}}
        echo  ${{github.workspace}}
        docker run -v ${{github.workspace}}:/workdir/scan ${{env.FINDSECBUG_IMAGE_TAG}}
        cat ${{github.workspace}}/secbugs-output.xml
    runs-on: ubuntu-latest
